source: ./site
destination: ./public
include: ['.htaccess', '.nojekyll']
name: Aron Griffis
title: Aron Griffis
email: aron@arongriffis.com
url: https://arongriffis.com
rss_description: Aron's Blog
kramdown:
  input: Pantsdown
pants:
  options: [1, 'named_entities', 'prevent_breaks']
defaults:
  - scope:
      path: ""
    values:
      layout: default
