source: ./site
destination: ./public
include: ['.htaccess', '.nojekyll']
name: Aron Griffis
title: Aron Griffis
email: aron@arongriffis.com
url: https://arongriffis.com
rss_description: Aron's Blog
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
sass:
  load_paths:
    - /home/vagrant/src/node_modules/susy/sass
defaults:
  - scope:
      path: ""
    values:
      layout: default
