source: ./site
destination: ./public
exclude: ['*.scss']
include: ['.htaccess', '.nojekyll']
name: Aron Griffis
title: Aron Griffis
email: aron@arongriffis.com
url: https://arongriffis.com
rss_description: Aron's Blog
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
defaults:
  - scope:
      path: ""
    values:
      layout: default